### ISSUE TITLE
Make the output console read-only

### ISSUE THREAD

**Issue by yihangho** [CS2103AUG2016-W11-C1/linenux#7]
Currently the output console is writable (see attached screencap), which doesn't make sense.

![untitled](https://cloud.githubusercontent.com/assets/4226956/19181531/33be950e-8ca0-11e6-831a-3c048952f570.gif)

This can be fixed by changing the UI component from `TextArea` to [`Label`](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Label.html) or [`Text`](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/Text.html).

**Comment by cadmusthefounder** [comment]
Done in exit branch
